// Login Page
export const LOGIN_FORM_INPUT_USERNAME = "lLOGIN_FORM_INPUT_USERNAME";
export const LOGIN_FORM_INPUT_PASSWORD = "LOGIN_FORM_INPUT_PASSWORD";
export const LOGIN_FORM_BUTTON_SUBMIT = "LOGIN_FORM_BUTTON_SUBMIT";
