/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/api";
import type {
  GetApiApprovalsQueryResponse,
  GetApiApprovalsHeaderParams,
} from "../types/GetApiApprovals.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/api";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getApiApprovalsSuspenseQueryKey = () =>
  [{ url: "/api/approvals" }] as const;

export type GetApiApprovalsSuspenseQueryKey = ReturnType<
  typeof getApiApprovalsSuspenseQueryKey
>;

/**
 * {@link /api/approvals}
 */
export async function getApiApprovalsSuspense(
  headers?: GetApiApprovalsHeaderParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiApprovalsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: `/api/approvals`,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return res.data;
}

export function getApiApprovalsSuspenseQueryOptions(
  headers?: GetApiApprovalsHeaderParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiApprovalsSuspenseQueryKey();
  return queryOptions<
    GetApiApprovalsQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiApprovalsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiApprovalsSuspense(headers, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * {@link /api/approvals}
 */
export function useGetApiApprovalsSuspense<
  TData = GetApiApprovalsQueryResponse,
  TQueryKey extends QueryKey = GetApiApprovalsSuspenseQueryKey,
>(
  headers?: GetApiApprovalsHeaderParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiApprovalsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getApiApprovalsSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getApiApprovalsSuspenseQueryOptions(headers, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
