/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/api";
import type {
  GetApiAccessRequestsQueryResponse,
  GetApiAccessRequestsHeaderParams,
} from "../types/GetApiAccessRequests.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/api";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiAccessRequestsQueryKey = () =>
  [{ url: "/api/access-requests" }] as const;

export type GetApiAccessRequestsQueryKey = ReturnType<
  typeof getApiAccessRequestsQueryKey
>;

/**
 * {@link /api/access-requests}
 */
export async function getApiAccessRequests(
  headers?: GetApiAccessRequestsHeaderParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiAccessRequestsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: `/api/access-requests`,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return res.data;
}

export function getApiAccessRequestsQueryOptions(
  headers?: GetApiAccessRequestsHeaderParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiAccessRequestsQueryKey();
  return queryOptions<
    GetApiAccessRequestsQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiAccessRequestsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiAccessRequests(headers, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * {@link /api/access-requests}
 */
export function useGetApiAccessRequests<
  TData = GetApiAccessRequestsQueryResponse,
  TQueryData = GetApiAccessRequestsQueryResponse,
  TQueryKey extends QueryKey = GetApiAccessRequestsQueryKey,
>(
  headers?: GetApiAccessRequestsHeaderParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiAccessRequestsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getApiAccessRequestsQueryKey();

  const query = useQuery(
    {
      ...getApiAccessRequestsQueryOptions(headers, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
