/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/api";
import type {
  GetApiApprovalsQueryResponse,
  GetApiApprovalsHeaderParams,
} from "../types/GetApiApprovals.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/api";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiApprovalsQueryKey = () =>
  [{ url: "/api/approvals" }] as const;

export type GetApiApprovalsQueryKey = ReturnType<
  typeof getApiApprovalsQueryKey
>;

/**
 * {@link /api/approvals}
 */
export async function getApiApprovals(
  headers?: GetApiApprovalsHeaderParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiApprovalsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: `/api/approvals`,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return res.data;
}

export function getApiApprovalsQueryOptions(
  headers?: GetApiApprovalsHeaderParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiApprovalsQueryKey();
  return queryOptions<
    GetApiApprovalsQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiApprovalsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiApprovals(headers, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * {@link /api/approvals}
 */
export function useGetApiApprovals<
  TData = GetApiApprovalsQueryResponse,
  TQueryData = GetApiApprovalsQueryResponse,
  TQueryKey extends QueryKey = GetApiApprovalsQueryKey,
>(
  headers?: GetApiApprovalsHeaderParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiApprovalsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getApiApprovalsQueryKey();

  const query = useQuery(
    {
      ...getApiApprovalsQueryOptions(headers, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
