/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/api";
import type {
  GetApiAccessRequestsIdQueryResponse,
  GetApiAccessRequestsIdPathParams,
  GetApiAccessRequestsIdHeaderParams,
} from "../types/GetApiAccessRequestsId.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/api";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiAccessRequestsIdQueryKey = (
  id: GetApiAccessRequestsIdPathParams["id"] | undefined,
) => [{ url: "/api/access-requests/:id", params: { id: id } }] as const;

export type GetApiAccessRequestsIdQueryKey = ReturnType<
  typeof getApiAccessRequestsIdQueryKey
>;

/**
 * {@link /api/access-requests/:id}
 */
export async function getApiAccessRequestsId(
  id: GetApiAccessRequestsIdPathParams["id"],
  headers?: GetApiAccessRequestsIdHeaderParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiAccessRequestsIdQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: `/api/access-requests/${id}`,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return res.data;
}

export function getApiAccessRequestsIdQueryOptions(
  id: GetApiAccessRequestsIdPathParams["id"] | undefined,
  headers?: GetApiAccessRequestsIdHeaderParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiAccessRequestsIdQueryKey(id);
  return queryOptions<
    GetApiAccessRequestsIdQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiAccessRequestsIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiAccessRequestsId(id!, headers, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * {@link /api/access-requests/:id}
 */
export function useGetApiAccessRequestsId<
  TData = GetApiAccessRequestsIdQueryResponse,
  TQueryData = GetApiAccessRequestsIdQueryResponse,
  TQueryKey extends QueryKey = GetApiAccessRequestsIdQueryKey,
>(
  id: GetApiAccessRequestsIdPathParams["id"] | undefined,
  headers?: GetApiAccessRequestsIdHeaderParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiAccessRequestsIdQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getApiAccessRequestsIdQueryKey(id);

  const query = useQuery(
    {
      ...getApiAccessRequestsIdQueryOptions(id, headers, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
