/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/api";
import type {
  GetApiAccessRequestsQueryResponse,
  GetApiAccessRequestsHeaderParams,
} from "../types/GetApiAccessRequests.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/api";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getApiAccessRequestsSuspenseQueryKey = () =>
  [{ url: "/api/access-requests" }] as const;

export type GetApiAccessRequestsSuspenseQueryKey = ReturnType<
  typeof getApiAccessRequestsSuspenseQueryKey
>;

/**
 * {@link /api/access-requests}
 */
export async function getApiAccessRequestsSuspense(
  headers?: GetApiAccessRequestsHeaderParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiAccessRequestsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: `/api/access-requests`,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return res.data;
}

export function getApiAccessRequestsSuspenseQueryOptions(
  headers?: GetApiAccessRequestsHeaderParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiAccessRequestsSuspenseQueryKey();
  return queryOptions<
    GetApiAccessRequestsQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiAccessRequestsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiAccessRequestsSuspense(headers, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * {@link /api/access-requests}
 */
export function useGetApiAccessRequestsSuspense<
  TData = GetApiAccessRequestsQueryResponse,
  TQueryKey extends QueryKey = GetApiAccessRequestsSuspenseQueryKey,
>(
  headers?: GetApiAccessRequestsHeaderParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiAccessRequestsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getApiAccessRequestsSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getApiAccessRequestsSuspenseQueryOptions(headers, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
