/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/api";
import type {
  GetApiAccessRequestsIdQueryResponse,
  GetApiAccessRequestsIdPathParams,
  GetApiAccessRequestsIdHeaderParams,
} from "../types/GetApiAccessRequestsId.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/api";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getApiAccessRequestsIdSuspenseQueryKey = (
  id: GetApiAccessRequestsIdPathParams["id"] | undefined,
) => [{ url: "/api/access-requests/:id", params: { id: id } }] as const;

export type GetApiAccessRequestsIdSuspenseQueryKey = ReturnType<
  typeof getApiAccessRequestsIdSuspenseQueryKey
>;

/**
 * {@link /api/access-requests/:id}
 */
export async function getApiAccessRequestsIdSuspense(
  id: GetApiAccessRequestsIdPathParams["id"],
  headers?: GetApiAccessRequestsIdHeaderParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiAccessRequestsIdQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: `/api/access-requests/${id}`,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return res.data;
}

export function getApiAccessRequestsIdSuspenseQueryOptions(
  id: GetApiAccessRequestsIdPathParams["id"],
  headers?: GetApiAccessRequestsIdHeaderParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiAccessRequestsIdSuspenseQueryKey(id);
  return queryOptions<
    GetApiAccessRequestsIdQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiAccessRequestsIdQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiAccessRequestsIdSuspense(id, headers, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * {@link /api/access-requests/:id}
 */
export function useGetApiAccessRequestsIdSuspense<
  TData = GetApiAccessRequestsIdQueryResponse,
  TQueryKey extends QueryKey = GetApiAccessRequestsIdSuspenseQueryKey,
>(
  id: GetApiAccessRequestsIdPathParams["id"],
  headers?: GetApiAccessRequestsIdHeaderParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiAccessRequestsIdQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getApiAccessRequestsIdSuspenseQueryKey(id);

  const query = useSuspenseQuery(
    {
      ...getApiAccessRequestsIdSuspenseQueryOptions(id, headers, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
