/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/api";
import type {
  PostApiAccessRequestsMutationRequest,
  PostApiAccessRequestsMutationResponse,
  PostApiAccessRequestsHeaderParams,
} from "../types/PostApiAccessRequests.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/api";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postApiAccessRequestsMutationKey = () =>
  [{ url: "/api/access-requests" }] as const;

export type PostApiAccessRequestsMutationKey = ReturnType<
  typeof postApiAccessRequestsMutationKey
>;

/**
 * {@link /api/access-requests}
 */
export async function postApiAccessRequests(
  data: PostApiAccessRequestsMutationRequest,
  headers?: PostApiAccessRequestsHeaderParams,
  config: Partial<RequestConfig<PostApiAccessRequestsMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostApiAccessRequestsMutationResponse,
    ResponseErrorConfig<Error>,
    PostApiAccessRequestsMutationRequest
  >({
    method: "POST",
    url: `/api/access-requests`,
    data: requestData,
    ...requestConfig,
    headers: {
      "Content-Type": "application/*+json",
      ...headers,
      ...requestConfig.headers,
    },
  });
  return res.data;
}

export function postApiAccessRequestsMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostApiAccessRequestsMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = postApiAccessRequestsMutationKey();
  return mutationOptions<
    PostApiAccessRequestsMutationResponse,
    ResponseErrorConfig<Error>,
    {
      data: PostApiAccessRequestsMutationRequest;
      headers?: PostApiAccessRequestsHeaderParams;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data, headers }) => {
      return postApiAccessRequests(data, headers, config);
    },
  });
}

/**
 * {@link /api/access-requests}
 */
export function usePostApiAccessRequests<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostApiAccessRequestsMutationResponse,
      ResponseErrorConfig<Error>,
      {
        data: PostApiAccessRequestsMutationRequest;
        headers?: PostApiAccessRequestsHeaderParams;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostApiAccessRequestsMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postApiAccessRequestsMutationKey();

  const baseOptions = postApiAccessRequestsMutationOptions(
    config,
  ) as UseMutationOptions<
    PostApiAccessRequestsMutationResponse,
    ResponseErrorConfig<Error>,
    {
      data: PostApiAccessRequestsMutationRequest;
      headers?: PostApiAccessRequestsHeaderParams;
    },
    TContext
  >;

  return useMutation<
    PostApiAccessRequestsMutationResponse,
    ResponseErrorConfig<Error>,
    {
      data: PostApiAccessRequestsMutationRequest;
      headers?: PostApiAccessRequestsHeaderParams;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostApiAccessRequestsMutationResponse,
    ResponseErrorConfig<Error>,
    {
      data: PostApiAccessRequestsMutationRequest;
      headers?: PostApiAccessRequestsHeaderParams;
    },
    TContext
  >;
}
