/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/api";
import type {
  PostApiAccessRequestsIdRejectMutationRequest,
  PostApiAccessRequestsIdRejectMutationResponse,
  PostApiAccessRequestsIdRejectPathParams,
  PostApiAccessRequestsIdRejectHeaderParams,
} from "../types/PostApiAccessRequestsIdReject.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/api";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postApiAccessRequestsIdRejectMutationKey = () =>
  [{ url: "/api/access-requests/:id/reject" }] as const;

export type PostApiAccessRequestsIdRejectMutationKey = ReturnType<
  typeof postApiAccessRequestsIdRejectMutationKey
>;

/**
 * {@link /api/access-requests/:id/reject}
 */
export async function postApiAccessRequestsIdReject(
  id: PostApiAccessRequestsIdRejectPathParams["id"],
  data: PostApiAccessRequestsIdRejectMutationRequest,
  headers?: PostApiAccessRequestsIdRejectHeaderParams,
  config: Partial<
    RequestConfig<PostApiAccessRequestsIdRejectMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostApiAccessRequestsIdRejectMutationResponse,
    ResponseErrorConfig<Error>,
    PostApiAccessRequestsIdRejectMutationRequest
  >({
    method: "POST",
    url: `/api/access-requests/${id}/reject`,
    data: requestData,
    ...requestConfig,
    headers: {
      "Content-Type": "application/*+json",
      ...headers,
      ...requestConfig.headers,
    },
  });
  return res.data;
}

export function postApiAccessRequestsIdRejectMutationOptions<
  TContext = unknown,
>(
  config: Partial<
    RequestConfig<PostApiAccessRequestsIdRejectMutationRequest>
  > & { client?: Client } = {},
) {
  const mutationKey = postApiAccessRequestsIdRejectMutationKey();
  return mutationOptions<
    PostApiAccessRequestsIdRejectMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: PostApiAccessRequestsIdRejectPathParams["id"];
      data: PostApiAccessRequestsIdRejectMutationRequest;
      headers?: PostApiAccessRequestsIdRejectHeaderParams;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data, headers }) => {
      return postApiAccessRequestsIdReject(id, data, headers, config);
    },
  });
}

/**
 * {@link /api/access-requests/:id/reject}
 */
export function usePostApiAccessRequestsIdReject<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostApiAccessRequestsIdRejectMutationResponse,
      ResponseErrorConfig<Error>,
      {
        id: PostApiAccessRequestsIdRejectPathParams["id"];
        data: PostApiAccessRequestsIdRejectMutationRequest;
        headers?: PostApiAccessRequestsIdRejectHeaderParams;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PostApiAccessRequestsIdRejectMutationRequest>
    > & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postApiAccessRequestsIdRejectMutationKey();

  const baseOptions = postApiAccessRequestsIdRejectMutationOptions(
    config,
  ) as UseMutationOptions<
    PostApiAccessRequestsIdRejectMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: PostApiAccessRequestsIdRejectPathParams["id"];
      data: PostApiAccessRequestsIdRejectMutationRequest;
      headers?: PostApiAccessRequestsIdRejectHeaderParams;
    },
    TContext
  >;

  return useMutation<
    PostApiAccessRequestsIdRejectMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: PostApiAccessRequestsIdRejectPathParams["id"];
      data: PostApiAccessRequestsIdRejectMutationRequest;
      headers?: PostApiAccessRequestsIdRejectHeaderParams;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostApiAccessRequestsIdRejectMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: PostApiAccessRequestsIdRejectPathParams["id"];
      data: PostApiAccessRequestsIdRejectMutationRequest;
      headers?: PostApiAccessRequestsIdRejectHeaderParams;
    },
    TContext
  >;
}
