/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/api";
import type {
  PostApiAccessRequestsIdApproveMutationResponse,
  PostApiAccessRequestsIdApprovePathParams,
  PostApiAccessRequestsIdApproveHeaderParams,
} from "../types/PostApiAccessRequestsIdApprove.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/api";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postApiAccessRequestsIdApproveMutationKey = () =>
  [{ url: "/api/access-requests/:id/approve" }] as const;

export type PostApiAccessRequestsIdApproveMutationKey = ReturnType<
  typeof postApiAccessRequestsIdApproveMutationKey
>;

/**
 * {@link /api/access-requests/:id/approve}
 */
export async function postApiAccessRequestsIdApprove(
  id: PostApiAccessRequestsIdApprovePathParams["id"],
  headers?: PostApiAccessRequestsIdApproveHeaderParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PostApiAccessRequestsIdApproveMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "POST",
    url: `/api/access-requests/${id}/approve`,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return res.data;
}

export function postApiAccessRequestsIdApproveMutationOptions<
  TContext = unknown,
>(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const mutationKey = postApiAccessRequestsIdApproveMutationKey();
  return mutationOptions<
    PostApiAccessRequestsIdApproveMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: PostApiAccessRequestsIdApprovePathParams["id"];
      headers?: PostApiAccessRequestsIdApproveHeaderParams;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, headers }) => {
      return postApiAccessRequestsIdApprove(id, headers, config);
    },
  });
}

/**
 * {@link /api/access-requests/:id/approve}
 */
export function usePostApiAccessRequestsIdApprove<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostApiAccessRequestsIdApproveMutationResponse,
      ResponseErrorConfig<Error>,
      {
        id: PostApiAccessRequestsIdApprovePathParams["id"];
        headers?: PostApiAccessRequestsIdApproveHeaderParams;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postApiAccessRequestsIdApproveMutationKey();

  const baseOptions = postApiAccessRequestsIdApproveMutationOptions(
    config,
  ) as UseMutationOptions<
    PostApiAccessRequestsIdApproveMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: PostApiAccessRequestsIdApprovePathParams["id"];
      headers?: PostApiAccessRequestsIdApproveHeaderParams;
    },
    TContext
  >;

  return useMutation<
    PostApiAccessRequestsIdApproveMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: PostApiAccessRequestsIdApprovePathParams["id"];
      headers?: PostApiAccessRequestsIdApproveHeaderParams;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostApiAccessRequestsIdApproveMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: PostApiAccessRequestsIdApprovePathParams["id"];
      headers?: PostApiAccessRequestsIdApproveHeaderParams;
    },
    TContext
  >;
}
