/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedApprovalsIndexRouteImport } from './routes/_protected/approvals/index'
import { Route as ProtectedAuditIndexRouteImport } from './routes/_protected/audit/index'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as ProtectedForbiddenIndexRouteImport } from './routes/_protected/forbidden/index'
import { Route as ProtectedRequestsIndexRouteImport } from './routes/_protected/requests/index'
import { Route as ProtectedRequestsIdRouteImport } from './routes/_protected/requests/$id'
import { Route as ProtectedRequestsNewRouteImport } from './routes/_protected/requests/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedApprovalsIndexRoute = ProtectedApprovalsIndexRouteImport.update({
  id: '/approvals/',
  path: '/approvals/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAuditIndexRoute = ProtectedAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedForbiddenIndexRoute = ProtectedForbiddenIndexRouteImport.update({
  id: '/forbidden/',
  path: '/forbidden/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRequestsIndexRoute = ProtectedRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRequestsIdRoute = ProtectedRequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRequestsNewRoute = ProtectedRequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/requests/$id': typeof ProtectedRequestsIdRoute
  '/requests/new': typeof ProtectedRequestsNewRoute
  '/approvals/': typeof ProtectedApprovalsIndexRoute
  '/audit/': typeof ProtectedAuditIndexRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
  '/forbidden/': typeof ProtectedForbiddenIndexRoute
  '/requests/': typeof ProtectedRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/requests/$id': typeof ProtectedRequestsIdRoute
  '/requests/new': typeof ProtectedRequestsNewRoute
  '/approvals': typeof ProtectedApprovalsIndexRoute
  '/audit': typeof ProtectedAuditIndexRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/forbidden': typeof ProtectedForbiddenIndexRoute
  '/requests': typeof ProtectedRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/requests/$id': typeof ProtectedRequestsIdRoute
  '/_protected/requests/new': typeof ProtectedRequestsNewRoute
  '/_protected/approvals/': typeof ProtectedApprovalsIndexRoute
  '/_protected/audit/': typeof ProtectedAuditIndexRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/forbidden/': typeof ProtectedForbiddenIndexRoute
  '/_protected/requests/': typeof ProtectedRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/requests/$id'
    | '/requests/new'
    | '/approvals/'
    | '/audit/'
    | '/dashboard/'
    | '/forbidden/'
    | '/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/requests/$id'
    | '/requests/new'
    | '/approvals'
    | '/audit'
    | '/dashboard'
    | '/forbidden'
    | '/requests'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/_protected/requests/$id'
    | '/_protected/requests/new'
    | '/_protected/approvals/'
    | '/_protected/audit/'
    | '/_protected/dashboard/'
    | '/_protected/forbidden/'
    | '/_protected/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/approvals/': {
      id: '/_protected/approvals/'
      path: '/approvals'
      fullPath: '/approvals/'
      preLoaderRoute: typeof ProtectedApprovalsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/audit/': {
      id: '/_protected/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof ProtectedAuditIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/forbidden/': {
      id: '/_protected/forbidden/'
      path: '/forbidden'
      fullPath: '/forbidden/'
      preLoaderRoute: typeof ProtectedForbiddenIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/requests/': {
      id: '/_protected/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof ProtectedRequestsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/requests/$id': {
      id: '/_protected/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof ProtectedRequestsIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/requests/new': {
      id: '/_protected/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof ProtectedRequestsNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedRequestsIdRoute: typeof ProtectedRequestsIdRoute
  ProtectedRequestsNewRoute: typeof ProtectedRequestsNewRoute
  ProtectedApprovalsIndexRoute: typeof ProtectedApprovalsIndexRoute
  ProtectedAuditIndexRoute: typeof ProtectedAuditIndexRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedForbiddenIndexRoute: typeof ProtectedForbiddenIndexRoute
  ProtectedRequestsIndexRoute: typeof ProtectedRequestsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedRequestsIdRoute: ProtectedRequestsIdRoute,
  ProtectedRequestsNewRoute: ProtectedRequestsNewRoute,
  ProtectedApprovalsIndexRoute: ProtectedApprovalsIndexRoute,
  ProtectedAuditIndexRoute: ProtectedAuditIndexRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedForbiddenIndexRoute: ProtectedForbiddenIndexRoute,
  ProtectedRequestsIndexRoute: ProtectedRequestsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
