/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as DevelopRouteImport } from './routes/develop'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedDasboardguruIndexRouteImport } from './routes/_protected/dasboard guru/index'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as ProtectedForbiddenIndexRouteImport } from './routes/_protected/forbidden/index'
import { Route as DevelopDasboardguruIndexRouteImport } from './routes/develop/dasboard guru/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopRoute = DevelopRouteImport.update({
  id: '/develop',
  path: '/develop',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDasboardguruIndexRoute =
  ProtectedDasboardguruIndexRouteImport.update({
    id: '/dasboard guru/',
    path: '/dasboard guru/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedForbiddenIndexRoute = ProtectedForbiddenIndexRouteImport.update({
  id: '/forbidden/',
  path: '/forbidden/',
  getParentRoute: () => ProtectedRoute,
} as any)
const DevelopDasboardguruIndexRoute =
  DevelopDasboardguruIndexRouteImport.update({
    id: '/dasboard guru/',
    path: '/dasboard guru/',
    getParentRoute: () => DevelopRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/develop': typeof DevelopRouteWithChildren
  '/login': typeof LoginRoute
  '/dasboard guru/': typeof ProtectedDasboardguruIndexRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
  '/forbidden/': typeof ProtectedForbiddenIndexRoute
  '/develop/dasboard guru/': typeof DevelopDasboardguruIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/develop': typeof DevelopRouteWithChildren
  '/login': typeof LoginRoute
  '/dasboard guru': typeof ProtectedDasboardguruIndexRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/forbidden': typeof ProtectedForbiddenIndexRoute
  '/develop/dasboard guru': typeof DevelopDasboardguruIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/develop': typeof DevelopRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/dasboard guru/': typeof ProtectedDasboardguruIndexRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/forbidden/': typeof ProtectedForbiddenIndexRoute
  '/develop/dasboard guru/': typeof DevelopDasboardguruIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/develop'
    | '/login'
    | '/dasboard guru/'
    | '/dashboard/'
    | '/forbidden/'
    | '/develop/dasboard guru/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/develop'
    | '/login'
    | '/dasboard guru'
    | '/dashboard'
    | '/forbidden'
    | '/develop/dasboard guru'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/develop'
    | '/login'
    | '/_protected/dasboard guru/'
    | '/_protected/dashboard/'
    | '/_protected/forbidden/'
    | '/develop/dasboard guru/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  DevelopRoute: typeof DevelopRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/develop': {
      id: '/develop'
      path: '/develop'
      fullPath: '/develop'
      preLoaderRoute: typeof DevelopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dasboard guru/': {
      id: '/_protected/dasboard guru/'
      path: '/dasboard guru'
      fullPath: '/dasboard guru/'
      preLoaderRoute: typeof ProtectedDasboardguruIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/forbidden/': {
      id: '/_protected/forbidden/'
      path: '/forbidden'
      fullPath: '/forbidden/'
      preLoaderRoute: typeof ProtectedForbiddenIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/develop/dasboard guru/': {
      id: '/develop/dasboard guru/'
      path: '/dasboard guru'
      fullPath: '/develop/dasboard guru/'
      preLoaderRoute: typeof DevelopDasboardguruIndexRouteImport
      parentRoute: typeof DevelopRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedDasboardguruIndexRoute: typeof ProtectedDasboardguruIndexRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedForbiddenIndexRoute: typeof ProtectedForbiddenIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDasboardguruIndexRoute: ProtectedDasboardguruIndexRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedForbiddenIndexRoute: ProtectedForbiddenIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface DevelopRouteChildren {
  DevelopDasboardguruIndexRoute: typeof DevelopDasboardguruIndexRoute
}

const DevelopRouteChildren: DevelopRouteChildren = {
  DevelopDasboardguruIndexRoute: DevelopDasboardguruIndexRoute,
}

const DevelopRouteWithChildren =
  DevelopRoute._addFileChildren(DevelopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  DevelopRoute: DevelopRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
