/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateAccessRequestDto = {
  /**
   * @minLength 1
   * @type string
   */
  clientRequestId: string;
  /**
   * @type integer, int32
   */
  applicationId: number;
  /**
   * @minLength 1
   * @type string
   */
  environment: string;
  /**
   * @minLength 1
   * @type string
   */
  accessLevel: string;
  /**
   * @minLength 1
   * @type string
   */
  justification: string;
  /**
   * @type string
   */
  policyVersion?: string | null;
};
