/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetApiAccessRequestsHeaderParams = {
  /**
   * @description Simulated User Email (e.g., alice@example.local, bob@example.local)
   * @type string | undefined
   */
  "X-User-Email"?: string;
};

/**
 * @description Success
 */
export type GetApiAccessRequests200 = any;

export type GetApiAccessRequestsQueryResponse = GetApiAccessRequests200;

export type GetApiAccessRequestsQuery = {
  Response: GetApiAccessRequests200;
  HeaderParams: GetApiAccessRequestsHeaderParams;
  Errors: any;
};
