/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetApiAccessRequestsIdPathParams = {
  /**
   * @type integer, int32
   */
  id: number;
};

export type GetApiAccessRequestsIdHeaderParams = {
  /**
   * @description Simulated User Email (e.g., alice@example.local, bob@example.local)
   * @type string | undefined
   */
  "X-User-Email"?: string;
};

/**
 * @description Success
 */
export type GetApiAccessRequestsId200 = any;

export type GetApiAccessRequestsIdQueryResponse = GetApiAccessRequestsId200;

export type GetApiAccessRequestsIdQuery = {
  Response: GetApiAccessRequestsId200;
  PathParams: GetApiAccessRequestsIdPathParams;
  HeaderParams: GetApiAccessRequestsIdHeaderParams;
  Errors: any;
};
