/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetApiApprovalsHeaderParams = {
  /**
   * @description Simulated User Email (e.g., alice@example.local, bob@example.local)
   * @type string | undefined
   */
  "X-User-Email"?: string;
};

/**
 * @description Success
 */
export type GetApiApprovals200 = any;

export type GetApiApprovalsQueryResponse = GetApiApprovals200;

export type GetApiApprovalsQuery = {
  Response: GetApiApprovals200;
  HeaderParams: GetApiApprovalsHeaderParams;
  Errors: any;
};
