/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostApiAccessRequestsIdApprovePathParams = {
  /**
   * @type integer, int32
   */
  id: number;
};

export type PostApiAccessRequestsIdApproveHeaderParams = {
  /**
   * @description Simulated User Email (e.g., alice@example.local, bob@example.local)
   * @type string | undefined
   */
  "X-User-Email"?: string;
};

/**
 * @description Success
 */
export type PostApiAccessRequestsIdApprove200 = any;

export type PostApiAccessRequestsIdApproveMutationResponse =
  PostApiAccessRequestsIdApprove200;

export type PostApiAccessRequestsIdApproveMutation = {
  Response: PostApiAccessRequestsIdApprove200;
  PathParams: PostApiAccessRequestsIdApprovePathParams;
  HeaderParams: PostApiAccessRequestsIdApproveHeaderParams;
  Errors: any;
};
