/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateAccessRequestDto } from "./CreateAccessRequestDto.ts";

export type PostApiAccessRequestsHeaderParams = {
  /**
   * @description Simulated User Email (e.g., alice@example.local, bob@example.local)
   * @type string | undefined
   */
  "X-User-Email"?: string;
};

/**
 * @description Success
 */
export type PostApiAccessRequests200 = any;

export type PostApiAccessRequestsMutationRequest = CreateAccessRequestDto;

export type PostApiAccessRequestsMutationResponse = PostApiAccessRequests200;

export type PostApiAccessRequestsMutation = {
  Response: PostApiAccessRequests200;
  Request: PostApiAccessRequestsMutationRequest;
  HeaderParams: PostApiAccessRequestsHeaderParams;
  Errors: any;
};
