/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RejectRequestDto } from "./RejectRequestDto.ts";

export type PostApiAccessRequestsIdRejectPathParams = {
  /**
   * @type integer, int32
   */
  id: number;
};

export type PostApiAccessRequestsIdRejectHeaderParams = {
  /**
   * @description Simulated User Email (e.g., alice@example.local, bob@example.local)
   * @type string | undefined
   */
  "X-User-Email"?: string;
};

/**
 * @description Success
 */
export type PostApiAccessRequestsIdReject200 = any;

export type PostApiAccessRequestsIdRejectMutationRequest = RejectRequestDto;

export type PostApiAccessRequestsIdRejectMutationResponse =
  PostApiAccessRequestsIdReject200;

export type PostApiAccessRequestsIdRejectMutation = {
  Response: PostApiAccessRequestsIdReject200;
  Request: PostApiAccessRequestsIdRejectMutationRequest;
  PathParams: PostApiAccessRequestsIdRejectPathParams;
  HeaderParams: PostApiAccessRequestsIdRejectHeaderParams;
  Errors: any;
};
